// Generated by CoffeeScript 1.4.0
//
// coffee -c canvas-01.coffee
//
(function() {
  var ctx;

  ctx = document.getElementById("game").getContext("2d");

  ctx.fillStyle = "#ff2200";

  ctx.fillRect(0, 0, ctx.canvas.width, ctx.canvas.height);

}).call(this);
